Azure/aztfexport

- internal/meta/hcl_schema.go
This might because the provider under used is a newer one than the version where we ingest the schema information.
This might happen when the user have some newer version provider installed in its local fs.
We simply remove that attribute from the config.
> Fix provider mismatch crash

- .tools/generate-provider-schema/generate-provider-schema/main.go
- README.md
- go.mod
- internal/armtemplate/armtemplate_test.go
- internal/meta/hcl_schema.go
- internal/meta/meta.go
- internal/meta/meta_impl.go
- internal/ui/aztfyclient/client.go
- internal/ui/importlist/importlist.go
- internal/ui/importlist/importlist_delegate.go
- internal/ui/importlist/item.go
- internal/ui/progress/progress.go
- internal/ui/ui.go
- main.go
aztfy has moved under Azure org.
Change path(go import / README) from magodo/aztfy to Azure/aztfy.
> Rename from magodo/aztfy to Azure/aztfy

- internal/meta/meta.go
- internal/meta/meta_impl.go
- internal/ui/importlist/importlist.go
- internal/ui/importlist/listkey.go
The interactive mode now has a keybinding `s`, which is used to allow users to save the typed resource mapping into the `.aztfyResourceMapping` file.
> new key binding `s`: save resoure mapping

- internal/meta/meta_impl.go
Fix the regression that the recommendation isn't taking effect due to the incorrect check of empty resource map.
> regression: the default recommendation doesn't work

- internal/meta/meta_impl.go
Always export the env var `AZURE_HTTP_USER_AGENT` when running `aztfy` so that the API from the AzureRM provider will append the `aztfy` in the `User-Agent` HTTP header.
> Recrod `aztfy` in `user-agent` HTTP header

- schema/provider_gen.go
terraform-provider-azurerm of current version is v3.0.1
ref https://github.com/hashicorp/terraform-provider-azurerm/compare/v3.0.0...v3.0.1
ref https://github.com/hashicorp/terraform-provider-azurerm/compare/v3.0.1...v3.0.2
`PROVIDER_DIR=/Users/sakabekodai/src/github.com/hashicorp/terraform-provider-azurerm PROVIDER_VERSION=3.0.2 make gen`
> Generate schema and resource id mapping for v3.0.2

- azure-pipelines.yml
- version.go
Set version in build pipeline. Though we shall make the version more explicit for users using `go install` or building from source, for the sake of identifying problems in issues, etc. But as this tool is one shot purpose, it is fine for now.
> Set version in build pipeline

- azure-pipelines.yml
- main.go
- version.go
To better clarify the issue
Set Git commit hash in the version.
- before
```console
$ ./bin/aztfy -v
v0.1.0
```
- after
```console
$ ./bin/aztfy -v                           
v0.1.0(16a3c20)
```
> Set revision in build pipeline

- LICENSE
This s is a legal attribution requirement under the MPLv2 license terms.
> Include in license file a copyright notice from the Hashicorp OSS project

- scripts/build.sh
`$OS_$ARCH` is resolved as `${OS_}${ARCH}` when epxanding the paramter, as in Bash the `_` is also a valid character as name. This PR explicitly set quote both variables with braces.
> Fix pipeline

- README.md
- internal/meta/tfinstall_find.go
- scripts/build.sh
Update TF version constraint to include v0.12, also mention the precondition in the README.
> Update TF version constraint to include v0.12

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
ref https://microsoft.github.io/code-with-engineering-playbook/developer-experience/devcontainers/
I would like to make more people can contribute to Azure Terrafy. 
1.  When someone develops Azure Terrafy, someone needs to set up a few things ready for the development environment. (e.g. [GoLang](https://go.dev/) / [Azure CLI](https://github.com/Azure/azure-cli) / [terraform](https://www.terraform.io/)) 
2. I want to enable e2e testing by switching to another environment without affecting my existing environment (Azure AD tenant, az config, terraform config, Go version, env, etc.).
I want to use a devcontainer to improve two things. ref https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers
> ## About dev containers
> Development …
> Adding a devcontainer

- go.mod
- go.sum
- internal/meta/tfinstall_find.go
Remove replace in go.mod and use github.com/magodo/hc-install directly. This is to avoid `go install` error due to `replace` directive used in go.mod, as is stated in https://github.com/golang/go/issues/44840. The fork can be later removed and using the upstream one, once https://github.com/hashicorp/hc-install/pull/52 is merged.
Fixes #80
> Remove replace in go.mod and use github.com/magodo/hc-install directly

- go.mod
- go.sum
- internal/meta/tfinstall_find.go
Depends on the official github.com/hashicorp/hc-install than my personal fork, as the PR is now merged: https://github.com/hashicorp/hc-install/pull/52.
> Use hashicorp/hc-intsall instead of the forked one

- go.mod
- go.sum
- internal/armtemplate/armtemplate.go
- internal/armtemplate/armtemplate_hack.go
- internal/armtemplate/armtemplate_test.go
- internal/meta/meta.go
- internal/meta/meta_dummy.go
- internal/meta/meta_impl.go
- internal/ui/aztfyclient/client.go
- main.go
This PR adds an additional step after getting the exported ARM template, to mitigate the issue that ARM template doesn't list some resource that is marked as `managedBy` other resource. Especially, we add a such case for managed disk when attatched to a VM, to fix #77.
> Post-ARM template export step for fixing some known ARM template issues

- internal/armtemplate/armtemplate.go
- internal/armtemplate/armtemplate_hack.go
- internal/armtemplate/armtemplate_test.go
- internal/client/client.go
- internal/meta/hcl_edit.go
- internal/meta/hcl_edit_test.go
- internal/meta/meta_impl.go
- internal/meta/terraform_hack.go
- internal/test/case_applicationinsight_webtest.go
- internal/test/e2e_test.go
Now the resource listing logic is as below:
- ARM template export into its raw format
- Populate managed resources on top of the ARM template
- Convert the ARM template raw format to fully qualified format with
subscription id and resource group name. Especially, the resource id
(both as the resource identifier and as the dependency) is converted
from its ARM resource id expression form, to its corresponding TF
resource id literal (this might requires some special transformation
based on the different formats used between ARM and TF)
From this point on, all the processing is on top of the FQ template,
with only the TF resource id taken into consideration. This makes a
change on the UI, where it previously showed the resource id in ARM
format, whilst now it shows the TF resource ID. This …
> Introduce Id transform during resource listing & Post HCL lifecycle addon 

- main.go
ref #32 Rename `-q` to `-b` to avoid confusion
#32 had not renamed the error message of `flagBatchMode`.
fix it.
> Fix error message

- internal/meta/importlist.go
- internal/meta/meta_impl.go
- internal/resmap/resmap.go
- internal/tfaddr/tf_addr.go
- internal/ui/common/progress.go
- internal/ui/importlist/importlist_delegate.go
- internal/ui/progress/progress.go
Previously, the saved resource mapping file only contains the items that have specified TF resource type. The skipped ones are absent. This is not friendly to resource group that has a large scale of resources, and the current auto deduction capability only provides users a limited set of resource types. This results into a lot of resources missing in the generated resource mapping file.
This PR changes this situation that all the resource listed via ARM template will be in the generated resource mapping file. The skipped ones will be left in the json object with empty string value. To simplify things, we regard empty `TFAddr.Type` as to be skipped in the import list. Especially, when importing with resource mapping file, we will not do auto deduction for resources, which means only the …
> Conslidate the user resource mapping file

- go.mod
- go.sum
- internal/ui/importlist/importlist.go
- internal/ui/importlist/listkey.go
This PR adds a new key map <kbd>delete</kbd> to mark the focused item as skipped, as is proposed in #114.
> UI: New key `delete` to mark item to be skipped

- internal/test/case_function_app_slot.go
- internal/test/e2e_test.go
Fix #123 
Test Result:
```shell
❯ AZTFY_E2E=1 go test -timeout=30m -v -run=TestFunctionAppSlot ./internal/test
=== RUN   TestFunctionAppSlot
=== PAUSE TestFunctionAppSlot
=== CONT  TestFunctionAppSlot
...
--- PASS: TestFunctionAppSlot (606.80s)
PASS
ok      github.com/Azure/aztfy/internal/test    606.940s
```
> Test: add a case for function app slot

- internal/ui/importlist/importlist.go
Fixed typo in the `No resource type recommendation available` error message.
> Fix typo in resource recommendation message

- internal/armtemplate/armtemplate.go
- internal/armtemplate/armtemplate_hack.go
- internal/test/case_storage_file_share.go
- internal/test/e2e_test.go
Fix #130.
```shell
💤  AZTFY_E2E=1 go test -timeout=30m -v -run="TestStorageFileShare" ./internal/test/...
=== RUN   TestStorageFileShare
=== PAUSE TestStorageFileShare
=== CONT  TestStorageFileShare
Initializing...
List resources...
Import resources...
Importing /subscriptions/67a9759d-d099-4aa8-8675-e6cfd669c3f4/resourceGroups/aztfy-rg-dvwhdtiv/providers/Microsoft.Storage/storageAccounts/aztfydvwhdtiv as azurerm_storage_account.test
[WARN] No mapping information for resource: /subscriptions/67a9759d-d099-4aa8-8675-e6cfd669c3f4/resourceGroups/aztfy-rg-dvwhdtiv/providers/Microsoft.Storage/storageAccounts/aztfydvwhdtiv/blobServices/default, skip it
[WARN] No mapping information for resource: /subscriptions/67a9759d-d099-4aa8-8675-e6cfd669c3f4/resourceGroups/aztfy-rg-dvwhdtiv/providers/Micros …
```
> Support storage file share

- internal/armtemplate/armtemplate_hack.go
- internal/test/case_signalr_service.go
- internal/test/e2e_test.go
Fix #154 
```shell
💤  AZTFY_E2E=1 go test -timeout=30m -v -run=TestSignalRService ./internal/test
=== RUN   TestSignalRService
=== PAUSE TestSignalRService
=== CONT  TestSignalRService
Initializing...
List resources...
Import resources...
Importing /subscriptions/67a9759d-d099-4aa8-8675-e6cfd669c3f4/resourceGroups/aztfy-rg-oyllyuvm/providers/Microsoft.SignalRService/signalR/test-oyllyuvm as azurerm_signalr_service.test
Importing /subscriptions/67a9759d-d099-4aa8-8675-e6cfd669c3f4/resourceGroups/aztfy-rg-oyllyuvm as azurerm_resource_group.test
Generating Terraform configurations...
--- PASS: TestSignalRService (237.15s)
PASS
ok      github.com/Azure/aztfy/internal/test    237.286s
```
> Normalize resource id for signalr service

- internal/meta/meta_impl.go
Update instruction when output directory is non-empty in interactive mode to allow users to choose either overwrite or append to the output directory.
> Update instruction when output directory is non-empty in interactive mode

- go.mod
- go.sum
- internal/meta/meta.go
- internal/run.go
- main.go
This PR makes several UI improvements:
- A tiny improvement on the output dir non-empty warning message, also ensure it is not shown in the `res` mode, as it is meant to be run non-interactively
- Removes the warning about missing mapping file when run in `rg` batch mode, which looks too verbose
- In `rg` batch mode and `res` mode, rather than printing the status line by line, use a spinner to show the current status, and optionally show some detail info.
`rg` batch mode
`res` mode
> Batch mode UI improvement

- go.mod
- go.sum
- internal/config/config.go
- internal/meta/meta_res.go
- internal/run.go
- main.go
For some cases (e.g. #197), aztft can't resolve the correct TF resource type as the assumption by aztft is no met. Whilst in that case, TF is still able to import that resource. Therefore, we need a way in single resource mode to allow users to explicitly set the TF resource type, similar as the resource mapping file used in rg batch mode.
Fix #197.
> Introduce `--type` in resource mode to allow users to explicitly set the TF resource type

- .github/workflows/pr.yaml
- go.mod
- go.sum
Fix data plane only resource id incorrectly prefixed by `\` after mapping from azure id to TF id by introducing the fix made in aztft.
Fix #229.
> Fix data plane only resource id incorrectly prefixed by `\` after mapping from azure id to TF id

- README.md
- internal/meta/meta_group_impl.go
- internal/resmap/resmap.go
- internal/test/cases/case_applicationinsight_webtest.go
- internal/test/cases/case_compute_vm_disk.go
- internal/test/cases/case_function_app_slot.go
- internal/test/cases/case_key_vault_nested_items.go
- internal/test/cases/case_signalr_service.go
- internal/test/cases/case_storage_file_share.go
- internal/test/utils.go
> Refactor resource mapping file

- internal/meta/meta_group.go
- internal/meta/meta_group_dummy.go
- internal/meta/meta_group_impl.go
- internal/run.go
- internal/ui/aztfyclient/client.go
- internal/ui/ui.go
> Export `.aztfySkippedResources.txt` to list skipped resources, if any

- go.mod
- go.sum
- internal/meta/meta_res.go
- internal/resourceset/azure_resource_set.go
- internal/resourceset/azure_resource_set_hack.go
- internal/run.go
> Offload handling property-like resources to aztft

- README.md
- internal/config/config.go
- internal/meta/meta.go
- internal/meta/meta_group.go
- internal/meta/meta_group_impl.go
- internal/run.go
- internal/test/cases/case_applicationinsight_webtest.go
- internal/test/cases/case_compute_vm_disk.go
- internal/test/cases/case_function_app_slot.go
- internal/test/cases/case_key_vault_nested_items.go
- internal/test/cases/case_signalr_service.go
- internal/test/cases/case_storage_file_share.go
- internal/ui/ui.go
- main.go
Related to #222
- In batch mode for `rg` and `query`, and also for `res`, `-g` will only generate resouce maping file, but not import any resource (interactive mode already has <kbd>s</kbd> for the same purpose)
- Remove the prefix dot of the resource mapping file and skipped resouces file names, to make it noticebale for Linux/Mac users
- `res` mode now also exports resource mapping file on a successful run (as a single azure resource might ends up with multiple TF resources)
- Making the key of resource mapping file case sensitive (to make the key usable for res mode)
> CLI option: `-g`/`--generate-mapping-file` to generate resource mapping file

- internal/config/config.go
- internal/meta/base_meta.go
- internal/meta/meta_dummy.go
- internal/run.go
- internal/ui/aztfyclient/client.go
- internal/ui/ui.go
- main.go
New option: `--hcl-only` to only keep the .tf files in the output directory, and removing the other files (e.g. state file).
Relating to #222
> New option: `--hcl-only` to only keep the .tf files in the output directory, and removing the others

- internal/meta/config_info.go
- internal/meta/hcl_edit.go
There are cases that multiple Azure resources correspond to the same TF resource id. E.g. parent and child resources, or an association resource and its master resource. In this case, when resolving cross resource dependencies, as we are depending on the TF resource id, we will ends up with multiple TF resources. There is no good way to tell which one of them is the exact depended resource. The only right thing to do is to add a comment containing all the candidates and let users to choose.
> Handle multiple azure resources have the same TF id when resolving TF dependency

- internal/meta/config_info.go
Avoid adding dependency when no cross reference exists, which avoid a panic when later adding dependencies to the HCL.
The way to reproduce this issue is to only import a subnet NSG association resource.
> Avoid adding dependency when no cross reference exists

- internal/meta/base_meta.go
- internal/utils/copyfile.go
`os.Rename()` doesn't work for Windows when moving files across drives. Copy by bytes instead.
Fix #267
> Avoid using `os.Rename()`

- internal/meta/base_meta.go
Don't merge state if import error in parallel import, which reveals the import error message in UI.
> Don't merge state if import error in parallel import

- go.mod
- go.sum
> Update dependency for aztft to fix the incorrect import spec for iotcentral app

- internal/config/config.go
- internal/meta/base_meta.go
- internal/test/query/query_test.go
- internal/test/resource/e2e_cases_test.go
- internal/test/resourcegroup/append_test.go
- internal/utils/dir_is_empty.go
- internal/utils/remove_everything.go
- main.go
Moving the interactive output dir check code from `NewBaseMeta()` to CLI before function as the `NewBaseMeta()` is meant to be used by 3rd-party modules, which is inappropriate to hold code requires user's interactions.
> Move the interactive output dir check code from `NewBaseMeta()` to CLI before function

- main.go
> CLI adds `--output json` when querying subscription id

- go.mod
- go.sum
- internal/config/config.go
- internal/log/log.go
- internal/meta/base_meta.go
- internal/meta/meta_map.go
- internal/meta/meta_query.go
- internal/meta/meta_res.go
- internal/meta/meta_rg.go
- internal/resourceset/azure_resource_set.go
- internal/ui/ui.go
- main.go
Adding `--log-level` to CLI option and add more logs.
> Adding log level to CLI option and add more logs

- README.md
Explicitly mention that a `where` predicate can contain multiple conditions in readme.md.
> README: Explicitly mention that a `where` predicate can contain multiple conditions

- internal/meta/base_meta.go
This might happen when all the resources failed to import with "--continue".
> Don't push state if there is no state to push

- go.mod
- go.sum
Fix the incorrect tfmerge version being used during the merge of #322: https://github.com/Azure/aztfy/pull/322/commits/61129a9ae3a73435ba8a7039c5d8e6b1008fcdf6#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R26
```shell
💤  AZTFY_E2E=1 go test -timeout=30m -run=TestAppendToModule ./internal/test/resourcegroup/... 
ok      github.com/Azure/aztfy/internal/test/resourcegroup      42.544s
```
> Fix the incorrect tfmerge version during a merge

- go.mod
- go.sum
- internal/meta/meta_map.go
- internal/meta/meta_query.go
- internal/meta/meta_res.go
- internal/meta/meta_rg.go
- internal/resourceset/azure_resource_set.go
- internal/run.go
- internal/ui.go
This PR parallelize the following processes during resource listing:
- Mapping Azure resources to TF resources, which under the hood call `aztft` (previously, this is done in serialize).
- Include the performance improvement on parallelism grainess in azlist: https://github.com/magodo/azlist/commit/8c0d57594436554f00c5fca349173382ceef9900
> Parallelize aztft and azlist

- go.mod
- go.sum
- internal/meta/base_meta.go
- main.go
Parallelize initializing provider in the importing directories. Without this, it takes a bunch of time to initialize when parallelism is high, e.g. `terraform init` takes 0.5 sec for one directory, which will multiply by the parallelism.
> Parallelize initializing provider in the importing directories

- README.md
- go.mod
- go.sum
- internal/meta/base_meta.go
- internal/meta/meta_dummy.go
- internal/meta/tfinstall_find.go
- internal/run.go
- internal/test/resourcegroup/append_test.go
- internal/test/resourcegroup/module_test.go
- internal/ui/aztfyclient/client.go
- main.go
- pkg/config/config.go
Previously, we were using `tfmerge` to merge the import state file and the base state file, by a per resource movement manner. This is fine in most cases. But there is still a space to improve the performance, when there is no base state given (i.e. not appending to an existing workspace). In this case, as long as the import items have no address conflicts (guaranteed by `aztfy`), it can safely merge the state files by simply appending (`resources` field). Also since this state file is a fresh new one, there is no special requirement on the `serial` and `lineage`.
This PR also makes some other less related changes to make it more intuitive for library users:
- Remove the rootdir (i.e. cache dir) creation from `NewMeta()`. The cache dir is only used to cache an auto-downloaded terraform …
> Optimize state merging process when there is no base state given

- internal/meta/base_meta.go
- pkg/config/config.go
For environment that has `dev_overrides` correctly setup for the providers, users can use `--dev-provider` to indicate instead of using the pinned version, use the local dev provider. Another effect of using `dev_overrides` is that it will not check the dependency lock for each terraform command, hence avoid calculating the provider hash everytime. This saves us a bit of CPU time, especially we are running `terraform` commands in parallel.
Therefore, this PR extends the `--dev-provider` a bit to not only remove the version constraint in the `terraform.tf`, it will also avoid the `terraform init` for the import directories, as the follow up terraform command will not use that file at all (given `dev_overrides`). This saves us some CPU time during `Init()`.
> Avoid `terraform init` for import workspaces when `--dev-provider` is specified

- internal/utils/remove_everything.go
- main.go
> Allow resource mapping file in the output directory in `map` mode

- main.go
`--hcl-only` is not expected to be used together with `--append` as it should not impact user's existing states. But in interactive mode, when usres press `N`, current implementation will leak in.
> Fix `--append` leaks to be used together with `--hcl-only` in interactive mode

- main.go
This PR changes the behavior of `-o` that it will create the output directory if not existed.
> Mkdir for output dir if not exists

- internal/test/resourcegroup/module_test.go
The module will needs to be initialized by `terrform init` for the `TestAppendToModule` test case, while it won't be called if `--dev-provider` is used.
> Test: suppress dev provider when running append to module test

- flag.go
- main.go
This PR adds one more tracing at the begining of the tool, to record the "effective" CLI being issued (which indicates that the flag resolving are taken into considerations, e.g. the default value is populated). Not all flags are being considered, where the non interesting flags and flags that may contain sensitive info are ignored.
> Add trace for effective CLI being issued (with non-interesting/sensitive flags removed)

- flag.go
- main.go
Previously, to use a different env rather than public cloud is only be possible to set the env var `ARM_ENVIRONMENT`. This PR introduces a new option `--env` to make it more discoverable.
Fix #288.
> New option: "--env"

- internal/meta/base_meta.go
- main.go
- pkg/config/config.go
The `-g` and <kbd>s</kbd> generates both a JSON versioned resource mapping file and the `import.tf` that is the new TF plannable import blocks, e.g.
```
>  cat import.tf
import {
id = "/subscriptions/xxxx/resourceGroups/AZTFY-VMDISK/providers/Microsoft.Compute/virtualMachines/aztfy-test/extensions/Microsoft.Azure.Monitor.AzureMonitorLinuxAgent"
to = azurerm_virtual_machine_extension.res-0
}
import {
id = "/subscriptions/xxxx/resourceGroups/AZTFY-VMDISK/providers/Microsoft.Compute/virtualMachines/aztfy-test/extensions/Microsoft.Azure.Security.Monitoring.AzureSecurityLinuxAgent"
to = azurerm_virtual_machine_extension.res-1
}
#...
```
Users are welcome to grab the `import.tf` and proceed the plannable import process for another importing experience that is provided by TF official.
This …
> Resource mapping file will now be generated together with the `import.tf` that is the TF plannable import blocks

- go.mod
- go.sum
> Update aztft to allow VM resolving fallback to `azurerm_virtual_machine`

- go.mod
- go.sum
Follow up of #425, related to #412
> Update aztft to move azurerm_virtual_machine out of skip list

- internal/meta/base_meta.go
Import block stops generate for skipped resources (same as the resource mapping file).
Otherwise, will hit error as reported at https://github.com/Azure/aztfexport/pull/425#issuecomment-1629148795
> Import block stops generate for skipped resources

- go.mod
- go.sum
Fix #435 
The upstream change is: https://github.com/magodo/aztft/commit/2b70a7a1cdd0e851dd7851fd49394af2cb9f8110
> Update aztft to statically build id for `azurerm_role_definition`

- auth_oidc.go
- command_before_func.go
- command_before_func_test.go
- flag.go
- main.go
This PR add supports for auth method Fedorated Workload Identity. In order to use this auth method for github, users need to follow up the https:registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_oidc to setup the SP and also the necessary env var. Then launch the command with option: `--use-oidc-cred`.
A example workflow can be found at: https:github.com/magodo/aztfy-oidc-test/blob/2eaad2c1f47cf369955fb7a1f715a05488faa48f/.github/workflows/test.yaml. Basically, following settings are required:
```
permissions:
id-token: write
contents: read
jobs:
test:
runs-on: ubuntu-latest
#...
- name: Export the demo rg using oidc
run:
aztfexport rg -n -f -use-oidc-cred --plain-ui my-rg
env:
ARM_USE_OIDC: true
ARM_TENANT_ID: ${{ secrets. ARM_TENANT_ID }} …
```
> New auth method: Fedorated Workload Identity (a.k.a OIDC)

- azure-pipelines.yml
- scripts/package/linux/build/Dockerfile
Avoid using 3rd-party Docker images in the pipeline, by:
- Build Linux packages directly on the VM, instead of doing it in the `ubuntu` image
- Skip Linux package download verification, which should be guaranteed by PMC. Which we previously uses `multiarch/qemu-user-static` image
> Avoid using 3rd-party Docker images: Build Linux packages directly on the VM && Skip Linux package download verification

- .gitignore
- flag.go
- internal/meta/base_meta.go
- internal/meta/config_info.go
- internal/meta/meta_query.go
- internal/meta/meta_res.go
- internal/meta/meta_rg.go
- internal/resourceset/azure_resource_set.go
- main.go
- pkg/config/config.go
This PR is to add support for exporting to azapi provider.
1. Add a new argument to specify the provider to export to. Currently support `azapi`.
2. Extract building common config from `main.go` as it is repeated too many times.
3. Do not add dependency in the resource if the parent resource contains the sub-resources' id in its body. This is to prevent the circular dependencies in the generated configuration.
> feature: add support for exporting to `azapi` provider

- command_before_func.go
- go.mod
- go.sum
- internal/meta/base_meta.go
- internal/meta/meta_dummy.go
- internal/run.go
- internal/ui/importlist/importlist.go
- internal/ui/importlist/importlist_delegate.go
- internal/ui/ui.go
- main.go
- pkg/config/config.go
This PR updates `tfadd` to involve the special handling for `azapi`: https://github.com/magodo/tfadd/pull/7, where it keeps some useful properties always converted from state, even if they are O+C, for its "partial" mode.
Since now `azapi` config generation is bound to a specific version as `azurerm` doesn, the provider version's default value is now also bound to the one defined in `tfadd`.
Meanwhile, this PR fixes some issuse for interactive mode, to adpot for `azapi`.
> Update `tfadd` to make azapi export more useful & UI adpotion for azapi

- internal/meta/base_meta.go
Provider block existance check for azapi. Otherwise, append mode will failed to init as there will be multiple provider configurations.
> Provider block existance check for azapi

- flag.go
Update the `ClientOptions.Telemetry.ApplicationID` to append the provider name, which is used in the `User-Agent` request header
> Update the `ClientOptions.Telemetry.ApplicationID` to append the provider name, which is used in the `User-Agent` request header

- flag.go
- go.mod
- go.sum
- internal/meta/extension_resource.go
- internal/meta/meta_query.go
- internal/meta/meta_rg.go
- main.go
- pkg/config/config.go
This PR updates the dependency on `azlist` (https://github.com/magodo/azlist/commit/835b23b44c11e60f0cc09c43923f68e6312debfd), where it adds support to list extension resources, and also include the resource groups that the listed resources belong to.
Based on that, we now introduced the following new options:
- `--include-resource-group`: This applies to the `query` mode, so that we can also export the resources together with their containing resource groups.
- `--include-role-assignment`: This applies to the `query` mode and `resource-group` mode. This option will export the role assignments **directly** assigned to any of the resources being exported. This means we won't export any of the inherited role assignments.
Fix #446
> `rg` and `query` modes add new option: `--include-role-assignment` & `query` mode add new option `--include-resource-group`

- internal/meta/base_meta.go
This PR fixes a missing corner case when exporting to azapi provider using an explicitly specified provider locally.
PS: This initialization step is not exposed for general use.
> Provider initialization using the terraform-client-import updates to adopt for azapi

- internal/meta/meta_rg.go
Fix `rg` mode not export empty resource group.
The reason is that `azlist` with `--include-resource-group` will only extend the resources listed with their including resource group(s). If there is no resource listed, then no resource group will be included.
> Fix `rg` mode not export empty resource group

- internal/meta/config_info.go
In https://github.com/Azure/aztfexport/pull/455, the `armid` package is updated to include the change https://github.com/magodo/armid/commit/7d1b8afd6ee1bc67d75176eb652579ecd31cd6be, which requires adoption in `aztfexport` to keep the cross rp parent-child dependencies.
E.g.
Before #455, and with this RP. We can get below when exporting a RG contains ACR:
```hcl
resource "azurerm_container_registry" "res-1" {
#...
depends_on = [
azurerm_resource_group.res-0,
]
}
```
But since #455 without this RP, we won't get the above `depends_on`.
> Fix cross RP parent-child dependency

- internal/test/resourcegroup/e2e_cases_test.go
- internal/test/utils.go
Makes test/non-test telemetry app id be of the same form `aztfexport(azurerm|azapi)`.
> Test telemetry app id be consistent as the non-test one

- flag.go
- internal/meta/base_meta.go
- internal/test/query/query_test.go
- internal/test/resmap/e2e_cases_test.go
- internal/test/resource/e2e_cases_test.go
- internal/test/resourcegroup/append_test.go
- internal/test/resourcegroup/hcl_only_test.go
- internal/test/resourcegroup/module_test.go
- main.go
- pkg/config/config.go
Previously, this tool by default will generate the `import.tf` as long as the `terraform` >= v1.5.0. Whilst this behavior will cause error when append to a workspace as a submodule, as the `import.tf` is only allowed to appear at the root module.
This PR fixes this issue by introducing a new option --generate-import-block` to allow users to select whether to generate the `import.tf`.
> New option: `--generate-import-block` to allow users to select whether to generate the import.tf

- go.mod
- go.sum
> Update aztft to include population of lb probe & rule

- .github/workflows/pr.yaml
- internal/meta/base_meta.go
- pkg/config/config.go
Add `ImportCallback` in the `Config` to allow caller inspect import status. Though, this is not directly used by this `aztfexport` CLI tool, while it is for future usage.
> Cfg: Add `ImportCallback` to allow caller inspect import status

- internal/meta/base_meta.go
- pkg/config/config.go
Internal usage only, won't impact CLI users.
> Internal: Split the ImportCallback to PreImportHook and PostImportHook, also add a new parameter `startTime`

- auth_oidc.go
- command_before_func.go
- command_before_func_test.go
- cred.go
- flag.go
- go.mod
- go.sum
- internal/meta/base_meta.go
- main.go
- pkg/config/auth_config.go
- pkg/config/config.go
Previously, there are some (though incomplete) authentication related flags, e.g. `--env`, `--use-azure-cli-cred`, these flags only affect the behavior of the `aztfexport` (e.g. listing resources), but won't be passed through to the providers. The providers' behaviors are only affected by either the `-provider-config` flag or by the environment of their owns.
The reason was there are a bunch of provider level properties (currently there are two providers). It would be a mass if we wrap all these flags and provide a bunch of flags back to users, and probably mentioning which set of flags are only usable for `azurerm` provider, and which are only for `azapi`.
However for the standview of the authentication, this separation brings a burden to users who will now need to take care of the two …
> Support full set of authentication configuration flags

- internal/meta/base_meta.go
- internal/meta/meta_dummy.go
- pkg/config/config.go
- pkg/meta/meta.go
This makes meta users to firstly import resources, then define the hook functions.
> Add `Set[Pre|Post]ImportHook` to BaseMeta interface

- flag.go
- go.mod
- go.sum
- internal/meta/base_meta.go
- main.go
- pkg/config/config.go
This PR adds new option `-mask-sensitive` to allow masking sensitive attributes. The masking is done by generating the zero value of that attribute, with a comment stating the reason. In non-full mode, those value will be trimed from the configuration, as they are of the zero values. While in the full mode, they are kept with the zero value + comments.
> New option: `-mask-sensitive` to allow masking sensitive attributes

- command_before_func.go
- command_before_func_test.go
- flag.go
- internal/meta/meta_res.go
- internal/test/cases/case_vnet.go
- internal/test/resmap/e2e_cases_test.go
- internal/test/resource/e2e_cases_test.go
- internal/test/resourcegroup/e2e_cases_test.go
- main.go
- pkg/config/config.go
- pkg/meta/meta.go
This PR extends the `aztfexport resource` subcommand, to allow multiple resource ids. The argument can be a list of mixtures of azure resource id, or a file path prefixed by `@`, which contains azure resource ids line by line.
Fix #550
Fix #545
> Resource mode supports multiple resources

- command_before_func.go
- internal/meta/base_meta.go
- main.go
Fix https://github.com/Azure/aztfexport/issues/476
> Behavior change of `--overwrite` to avoid deleting user files

- go.mod
- go.sum
- internal/meta/meta_query.go
- internal/meta/meta_rg.go
`azlist` errors are wrapped now that users can differentiate error types from the `List()` call.
> Wrapping azlist error

- internal/meta/base_meta.go
Previously, when using terraformless export (i.e. `-tfclient-plugin-path`), if the resource/resource group to be exported doesn't exit, an empty HCL block will still be generated.
This PR adds additional check after the ReadResource RPC call, to raise error if the state read is nil. This logic exists in `terraform` (@internal/terraform/node_resource_import.go), that's why terraform export will correctly raise the error for non-existent resources.
> Return error for non-existent resources when using terraformless export

- internal/meta/base_meta.go
This is due to the original way of disabling RP registration is now deprecated in the latest v4 azurerm provider.
> Using `resource_provider_registrations` to skip registration of RP

- .github/workflows/pr.yaml
- command_before_func.go
- flag.go
- go.mod
- go.sum
- internal/meta/meta_query.go
- main.go
- pkg/config/config.go
This PR adds support for `--arg-table` and `--arg-authorization-scope-filter` in query mode.
- `--arg-table`: This allows users to specify ARG table name other than the "Resources" (default) table. See https://learn.microsoft.com/en-us/azure/governance/resource-graph/concepts/query-language#resource-graph-tables for the complete list
- `--arg-authorization-scope-filter`: This allows users to modify the authZ scope filter parameter in the ARG query. Detailed information can be found at: https://learn.microsoft.com/en-us/azure/governance/resource-graph/concepts/query-language#query-scope
Fix https://github.com/Azure/aztfexport/issues/550
> Query mode: Supports `--arg-table` and `--arg-authorization-scope-filter`

- internal/meta/base_meta.go
- main.go
This adds up the provider configs that are possible to be configured via environment variables to the tfclient, which can only be added during initialization phase.
> Setup the env var only provider configs for tfclient

- go.mod
- go.sum
Update dep for aztft (to support azurerm v4.5.0)
> Update dep for aztft (to support azurerm v4.5.0)

- internal/meta/meta_rg.go
This PR is an improvement on https://github.com/Azure/aztfexport/pull/500, that we leverages the `azlist` to include the resource group being listed as part of the resource list. The benefit of this is that `azlist` will pick up any extension resources for the resource list, including the resoruce group itself (which solves the #573). The only thing need special handling is that for empty resource group, the resource group won't be listed, in which case we'll have to manually add the resource group to the resource list.
Fix https://github.com/Azure/aztfexport/issues/573
> RG mode: uses `azlist` with rg included, with special handling for empty rg

- internal/meta/meta_rg.go
This PR is a fix for the #574, which doesn't handle exporting the extension resources assigned to an empty resource group. The reason is that `azlist` by default query resources from the ARG `Resources` table, if a resource group is empty, then the query by resource group name won't return any resource, and we end up explicitly add this empty resource group to the resource list, but didn't check if any ext resource exists on it.
This PR fixes this by firstly listing the RG itself, with any ext resource if any, from the `ResourceContainers` table. Then, if the RG exists, we'll further list the resources in it, including the ext resources, from the `Resources` table.
Fix #573. Supersedes #575.
A non-empty RG:
An empty RG:
> RG mode: Two step list, rg itself (incl. ext), then resources (incl. ext) in it

- internal/meta/tfinstall_find.go
Removing the version check as most users are now at version later than 0.12.0. Also, the version check will not accept dev version, which is an unnecessary restrict.
Relating to: https://github.com/Azure/aztfexport/issues/582
> tfinstall: Remove version check

- internal/meta/meta_dummy.go
- pkg/meta/meta.go
- pkg/meta/meta_test.go
Adds new function `NewDummyMeta` that does not call any external API on import. This is useful for integration testing use case.
> `pkg/meta`: New function `NewDummyMeta` to export the DummyMeta implementation

- internal/meta/base_meta.go
- internal/meta/config_info.go
- internal/meta/hcl_edit.go
- internal/meta/hcl_edit_test.go
Improved export logic such that when resourceId-valued attribute is matched against a dependency resource, use implicit TF address instead of depends_on syntax.
Config exported in previous behaviour:
```
// The id of this resource is "/subscription/123/resourceGroup/123/providers/Foo/foo/foo1"
resource "azurerm_foo_resource" "example" {
name = "foo1"
}
resource "azurerm_bar_resource" "example" {
name = "bar1"
foo_id = "/subscription/123/resourceGroup/123/providers/Foo/foo/foo1"
depends_on = [
azurerm_foo_resource.example
]
}
```
Config exported in the new behaviour:
```
resource "azurerm_foo_resource" "example" {
name = "foo1"
}
resource "azurerm_bar_resource" "example" {
name = "bar1"
foo_id = azurerm_foo_resource.example.id
}
```
If no such value is found, it will still fall-back to …
> Use implicit dependency instead of depends_on

- go.mod
- go.sum
Update `tfadd` to involve the fix: https://github.com/magodo/tfadd/commit/d62ece5d26d793a4c3ffee9bd4dc8be7b65d6cd7
Fix #626
> Update tfadd for a fix to remove zero/default value attribute only for optional attribute

- go.mod
- go.sum
- internal/meta/meta_res.go
Update azlist for the updated arm schemas
> Update azlist for the updated arm schemas

- internal/meta/meta_query.go
- internal/meta/meta_res.go
- internal/meta/meta_rg.go
- internal/resourceset/azure_resource_set.go
- internal/resourceset/azure_resource_set_hack.go
With #643, the resource mode will always need to use `azlist` to do a GET for each resource, no matter if it is necessary or not. Due to the design of `azlist`, it internally uses a resource type file to lookup the correct API versions to use for each resource type. This might cause issues if the resource type is a relatively new one, which is not available in the (outdated) resource type file (see: #648).
Instead, if the user doesn't need to query more resources than what are specified (e.g. child resource, extension resource, etc.), there is no need to call into `azlist`. In this case, we can simply return the resource set as is specified.
Additionally, this PR removes the `Properties` from type `resourceset.AzureResource`. The `Properties` are meant to be returned from `azlist`, and is …
> Resource mode: Avoid the API calls (and any potential error) if only exporting for the specified resources
