.goreleaser.yml
go.mod
go.sum
internal/meta.go
internal/run.go
main.go
version.go

Retry on import error

---

internal/meta/auth.go

This PR adds support for Azure clouds other than public.

Support other cloud

---

README.md

Update README.md to add links to additional useful resources.

Update README.md to add links to additional useful resources

---

README.md

Update README.md to removing the `terraform add` part as we are no longer depends on it, instead on `tfadd`.

Update README.md to removing the `terraform add` part

---

go.mod
go.sum

Update schema for v3.6.0

---

README.md

README.md: mention the expected user input in interactive mode

---

README.md

Add instructions about how to use remote backend.

README: add instructions about how to use remote backend

---

internal/ui/importlist/importlist.go

The filter mode (invoked via <kbd>/</kbd>) now supports regexp, as proposed by #114.

Filter supports regexp

---

internal/armtemplate/armtemplate_hack.go

Fix #118. The test is omitted since there are plan diff due to issues from provider.

ID transformation for frontdoor

---

internal/client/client.go

Client initialization option set cloud config

---

internal/client/client.go

See https://github.com/Azure/terraform-provider-azapi/pull/151 for context.

Optionally set environment variable for azcore

---

internal/config/config.go
internal/meta/meta.go
main.go

New option: `--dev-provider` to allow local development provider

---

go.mod
go.sum

Update aztft dep

---

go.mod
go.sum

Update dependencies for aztft

---

internal/run.go

Show import progress on rg batch mode.

Show import progress on rg batch mode

---

go.mod
go.sum
version.go

Dep: update tfadd for provider v3.17.0

Dep: update tfadd for provider v3.17.0

---

go.mod
go.sum

Update dependencies for provider v3.20.0

Update dependencies for provider v3.20.0

---

internal/meta/meta.go

Update interactive message for overwrite/append

---

internal/meta/meta.go

Fix the missing part in #202

---

go.mod
go.sum
internal/config/config.go
internal/meta/meta.go
main.go

New common option: `--full-config` to generate full HCL from TF state

---

azure-pipelines.yml

Modify service connection

---

go.mod
go.sum

Upgrade dep for provider v3.23.0

Upgrade dep for provider v3.23.0

---

README.md
internal/config/config.go
internal/meta/meta.go
main.go

Renaming `--batch`/`-b` to `--non-interactive`/`-n`.
Relating to #222.

Renaming `--batch`/`-b` to `--non-interactive`/`-n`

---

main.go

Remove the before func, inline in each cmd

Remove the before func, inline in each cmd

---

internal/config/config.go
internal/run.go
internal/test/query/query_test.go
internal/test/resmap/e2e_cases_test.go
internal/test/resource/e2e_cases_test.go
internal/test/resourcegroup/append_test.go
internal/test/resourcegroup/e2e_cases_test.go
main.go

Bring the before func to command level. Also brings the log path and continue on error flags to the cfg.

Bring the before func to command level

---

azure-pipelines.yml

Create the git tag with the specified version during the pipeline run via the *azure-terraform-bot* account.

Pipeline: create git tag during the pipeline via a bot account

---

azure-pipelines.yml

Pipeline will now create a pr to homebrew to upgrade the formula for new version.
Related with #143.

Pipeline pr to homebrew

---

azure-pipelines.yml

Pipeline will now submit a PR to winget-pkgs for each release.
Relating to #143. Ping @andrew-flatters-bliss.

Pipeline: PR to winget-pkgs

---

go.mod
go.sum

Update azlist to include a fix. Fix #257.

Update azlist to include a fix

---

.github/workflows/pr.yaml
internal/client/client.go
internal/meta/base_meta.go
internal/test/random.go
internal/ui/common/progress.go
internal/utils/copyfile.go
internal/utils/writefile.go
main.go

Integrating `gosec` to CI, which is for internal security compliance.

Integrate with `gosec` to CI

---

.github/workflows/codeql.yml

Integrate `codeql` to CI

---

azure-pipelines-ci.yml

Integrate `credscan` (in ADO) to CI

Integrate `credscan` to CI

---

go.mod
go.sum

Update azlist dep to fix panic on resource without id

---

go.mod
go.sum

Update azlist for supporting cloud other than Azure public

---

internal/meta/meta_res.go

resource mode: Fix TF address conflict on multiple same typed prop-like resources

---

go.mod
go.sum

Update dependency for aztft to fix the incorrect import spec for dns zone

---

go.mod
go.sum

Update dependency for aztft to fix the incorrect import spec for automation source control

---

go.mod
go.sum

Update aztft to include the deprecation of  `azurerm_monitor_scheduled_query_rules_alert`

---

go.mod
go.sum

Update dep for provider v3.38.0

Update dep for provider v3.38.0

---

internal/test/cases/case_compute_vm_disk.go

Update acctest for compute: ubuntu image 16.04->18.04

---

internal/resourceset/azure_resource_set.go
internal/ui/ui.go

Fix mis-using Go `log` pkg

---

go.mod
go.sum
main.go

This PR adds a new hiddent option `--profile <cpu|mem>` to help developer to profile the performance of `aztfy`.

New hidden option: `--profile <cpu|mem>`

---

index.html

typo in slide

---

internal/meta/base_meta.go
pkg/config/config.go

`Config.ProviderConfig` supports flexible attributes

`Config.ProviderConfig` supports flexible attributes

---

main.go

Fixing grammar or clarity on specific prompts to help with usability.

Update help prompts and outputs

---

go.mod
go.sum

Update dep for provider v3.46.0

Update dep for provider v3.46.0

---

command_before_func_test.go
flag.go

This is a follow up PR for #376 after #374 is merged.

Add test case and CLI trace for the newly added flag: --provider-version

---

internal/meta/base_meta.go

The previous code is not tested and is actually not working.

Fix a bug during provider config setting

---

go.mod
go.sum

Update azlist to include: https://github.com/magodo/azlist/commit/58631213ca2cc1c1880ff08e3511232b4b9e1908

Update azlist to eliminate child resource listing for problematic resource types

---

azure-pipelines.yml

This PR migrates the Linux package publish pipeline to using vNext PMC platform, which is a MS internal requirement.

PMC migration to vNext

---

go.mod
go.sum

Update aztft to support populate logic app workflow's prop-like resources

---

flag.go
main.go

CLI: Expose `--plain-ui` to be used in environment that has no /dev/tty

---

azure-pipelines.yml

Update pipeline to use PMC container instead of PMC pip package to avoid dependency issues.

Pipeline update

---

go.mod
go.sum

Update aztft to fix a panic when querying unknown resource types

---

azure-pipelines.yml

Add SBOM task for the release pipeline.

CI: Add SBOM task

---

azure-pipelines-ci.yml

Cred scan v3

---

internal/run.go

Non-interactive mode error out if no resource being listed

---

go.mod
go.sum

Dep: Update aztft to correct the populated resource id of `azurerm_network_interface_application_security_group_association`

---

flag.go
internal/meta/base_meta.go
internal/meta/base_meta_test.go
internal/meta/meta_map.go
internal/meta/meta_query.go
internal/meta/meta_res.go
internal/meta/meta_rg.go
internal/test/query/query_test.go
main.go
pkg/config/config.go

New options to exclude resources to be exported: `--exclude-[terraform|azure]-resource(-file)`

---

go.mod
go.sum

Update aztft and tfadd to support azurerm v4.33.0 and azapi v2.4.0

Update aztft and tfadd to support azurerm v4.33.0 and azapi v2.4.0

---

go.mod
go.sum

See: https://github.com/advisories/GHSA-2x5j-vhc8-9cwm

Update tfadd to transitively update github.com/cloudflare/circl to v1.6.1

---

internal/meta/base_meta.go
internal/meta/meta_dummy.go
internal/run.go
internal/ui/aztfexportclient/client.go
internal/ui/importlist/importlist.go

Refactor `BaseMeta`: Add `Get(SkippedResources|ImportBlocks)` to provide a more friendly API.

Refactor `BaseMeta`: Add `Get(SkippedResources|ImportBlocks)`

---

internal/meta/base_meta.go
internal/meta/meta_dummy.go
internal/run.go
internal/ui/aztfexportclient/client.go

Refactor `BaseMeta`: Add `GetTerraformCfg`
